on:
  schedule:
    - cron: '0 20 * * 1'  # Every Monday at 8 PM GMT (so no later than 7am Tuesday morning in Melbourne)
  push:
    branches: [main]
jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::cranlogs
            any::desc
            any::dplyr
            any::gh
            any::jsonlite
            any::pkgsearch
            any::purrr
            any::remotes
            any::stringr
            any::tibble
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find packages
        run: Rscript find_packages.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Data updated' || echo "No changes to commit"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
